# Generated by Django 2.0.1 on 2018-01-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_chapitre', models.CharField(max_length=200)),
                ('acquis', models.BooleanField()),
                ('progression', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('degre_difficult', models.IntegerField()),
                ('degre_preference', models.IntegerField()),
                ('note_esperee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date published')),
                ('heureDebut', models.DateTimeField()),
                ('heureFin', models.DateTimeField()),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kluge_arbeit.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('filiere', models.CharField(max_length=200)),
                ('tps_concentration', models.IntegerField()),
                ('ordre_travail', models.IntegerField()),
                ('fiche_lecture', models.IntegerField()),
                ('start_difficult', models.IntegerField()),
                ('start_preference', models.IntegerField()),
                ('tps_pause', models.IntegerField()),
                ('supplementaire', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='seance',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kluge_arbeit.Utilisateur'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kluge_arbeit.Matiere'),
        ),
    ]
